    # include <stdio.h>

    # include <stdlib.h>
    # include <conio.h>
    main()
    {
    float jumlah,rerata,nilai;
    char *nama,IP,index;
    printf("\n=================================================");
    printf(" program menentukan Index dan IP serta nilai rerata MK DPK dari 10 mahasiswa");
    printf("\n=================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-1 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f",&nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A', IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s", nama);
    printf("\nnilai MK DPK \t\t: %.2f", nilai);
    printf("\nIndex nilai \t\t: %c", index);
    printf("\nIPK \t\t\t: %d.00", IP);
    jumlah = jumlah+nilai;
    getch ();
    system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-2 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s", nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIPK \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-3 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-4 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-5 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-6 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-7 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\IP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-8 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-9 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n=================================================");
    printf("\n\n\t\t\t << Mahasiswa Ke-10 >>");
    printf("\n\nMasukan nama mahasiswa \t: ");
    gets(nama);
    printf("masukan nilai MK DPK \t: ");
    scanf("%f", &nilai);
    if(nilai<=40)(index = 'D', IP = 1);
    else if(nilai<=60) (index = 'C', IP = 2);
    else if(nilai<=80) (index = 'B', IP = 3);
    else if (nilai<=100) (index = 'A',IP = 4);
    printf("\n\n\t\tDATA MAHASISWA \t: ");
    printf("\n=============================================>");
    printf("\n\nNama Mahasiswa \t\t: %s",nama);
    printf("\nnilai MK DPK \t\t: %.2f",nilai);
    printf("\nIndex nilai \t\t: %c",index);
    printf("\nIP \t\t\t: %d.00",IP);
    jumlah = jumlah+nilai;
    getch (); system ("cls");
    printf("\n\n======================= ( Rata - Rata) ==============");
    rerata = jumlah/10;
    printf("\nRata-rata nilai 10 mahasiswa \t\t= %.2f",rerata);
    if(rerata<=40) index = 'D';
    else if(rerata<=60) index = 'C';
    else if(rerata<=80) index = 'B';
    else index = 'A';
    printf("\nIndex nilai 10 mahasiswa \t\t: %c", index);
    getch();
    system ("cls");
    getch ();
    return 0;
    }           
